/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.ewebcomputing.printtexts;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int add=0x7f020000;
        public static final int balance=0x7f020001;
        public static final int briefcase=0x7f020002;
        public static final int cash_register=0x7f020003;
        public static final int delete=0x7f020004;
        public static final int dollar=0x7f020005;
        public static final int home=0x7f020006;
        public static final int loading=0x7f020007;
        public static final int shopping_cart=0x7f020008;
        public static final int solid_blue=0x7f02000c;
        public static final int solid_green=0x7f02000d;
        public static final int solid_red=0x7f02000b;
        public static final int solid_white=0x7f02000e;
        public static final int splash=0x7f020009;
        public static final int trans_blue=0x7f02000f;
        public static final int wallet=0x7f02000a;
    }
    public static final class id {
        public static final int AMOUNT=0x7f060007;
        public static final int CUSTOMER=0x7f060006;
        public static final int ITEM=0x7f060008;
        public static final int QTY=0x7f060009;
        public static final int SaveTransaction=0x7f06000d;
        public static final int bal_cash=0x7f060002;
        public static final int bal_cashlabel=0x7f060001;
        public static final int bal_check=0x7f060004;
        public static final int bal_checklabel=0x7f060003;
        public static final int ballabel=0x7f060000;
        public static final int debtorsheader=0x7f060005;
        public static final int email=0x7f06000c;
        public static final int itemlabel=0x7f06000b;
        public static final int txnlabel=0x7f06000a;
    }
    public static final class layout {
        public static final int balanceactivity=0x7f030000;
        public static final int debtoractivity=0x7f030001;
        public static final int debtorheader=0x7f030002;
        public static final int debtorrow=0x7f030003;
        public static final int group=0x7f030004;
        public static final int home=0x7f030005;
        public static final int inventoryactivity=0x7f030006;
        public static final int invheader=0x7f030007;
        public static final int invrow=0x7f030008;
        public static final int mailactivity=0x7f030009;
        public static final int main=0x7f03000a;
        public static final int msgrow=0x7f03000b;
        public static final int splash=0x7f03000c;
        public static final int txnheader=0x7f03000d;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
    }
    public static final class style {
        /** <item name="android:colorForeground">#fff</item>
<item name="TextColor">@drawable/solid_red</item>
<item name="android:windowFrame">@drawable/screen_frame</item>
<item name="android:windowBackground">@drawable/solid_red</item>
<item name="panelForegroundColor">#FF000000</item>
<item name="panelBackgroundColor">#FFFFFFFF</item>
<item name="panelTextColor">#FF000000</item>
<item name="panelTextSize">14</item>
<item name="menuItemTextColor">#FF000000</item>
<item name="menuItemTextSize">14</item>
         */
        public static final int CustomTheme=0x7f050000;
        public static final int Theme_Background=0x7f050001;
        public static final int Theme_NoBackground=0x7f050002;
    }
}
